using System.Windows.Markup;

[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.AcManagersNew")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.AcObjectsNew")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.ContentInstallation")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.ContentInstallation.Entries")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Data")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.GameProperties")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Helpers")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Helpers.AcLog")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Helpers.AcSettings")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Helpers.DirectInput")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Helpers.PresetsPerMode")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Managers")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Managers.Plugins")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Managers.Online")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Miscellaneous")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Objects")]
[assembly: XmlnsDefinition("http://acstuff.club/app/tools", "AcManager.Tools.Profile")]
[assembly: XmlnsPrefix("http://acstuff.club/app/tools", "t")]